//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.24 at 12:18:09 PM CET 
//


package com.rapidminer.openml.task;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.rapidminer.openml.task.jaxb.beans.DataSetDescription;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rapidminer.openml.task package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataSetDescription_QNAME = new QName("http://openml.org/data-des-description", "data-set-description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rapidminer.openml.task
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataSetDescription }
     * 
     */
    public DataSetDescription createDataSetDescription() {
        return new DataSetDescription();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSetDescription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openml.org/data-des-description", name = "data-set-description")
    public JAXBElement<DataSetDescription> createDataSetDescription(DataSetDescription value) {
        return new JAXBElement<DataSetDescription>(_DataSetDescription_QNAME, DataSetDescription.class, null, value);
    }

}
