<div class="container">
    <div class="marketing" style="margin-top:10px;margin-left:auto;margin-right:auto;">
        <h1>OpenML API</h1>
        <p class="marketing-byline">connect, create</p>
    </div>
    <hr class="softennarrow" />
    <!-- Docs nav
        ================================================== -->
    <div class="row">
        <div class="span3 bs-docs-sidebar" style="min-height:600px;">
            <ul class="nav nav-list bs-docs-sidenav">

[[[MENU]]]

			</ul>
        </div>
        <div class="span9">
            <div class="tab-content2">
                <h2>REST Services <small></small></h2>
                <p>REST is the simplest request format to use - it's a simple HTTP GET or POST action. The REST Endpoint URL is <pre>http://expdb.cs.kuleuven.be/expdb/api/</pre></p>
                <p>For instance, to request the <code>openml.data.description</code> service, invoke like this:<pre>http://expdb.cs.kuleuven.be/expdb/api/?f=openml.data.description&data_id=1</pre></p>
                <p>Responses are always in XML format, also when an error is generated by the system. Error messages will look like this:
<pre>&lt;oml:error xmlns:oml="http://openml.org/error"&gt;
  &lt;oml:code&gt;100&lt;/oml:code&gt;
  &lt;oml:message&gt;Please invoke legal function&lt;/oml:message&gt;
  &lt;oml:additional_information&gt;Additional information, not always available. &lt;/oml:additional_information&gt;
&lt;/oml:error&gt;
</pre>
				The error codes and messages are explained in the appropriate function. </p>
				
[[[FUNCTIONS]]]

			</div>
        </div>
        <!-- end span9 -->
    </div>
    <!-- end row -->
</div>
<!-- end container -->