//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.27 at 12:54:20 PM CET 
//


package com.rapidminer.openml.task.jaxb.beans;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for cross-validation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="cross-validation">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="number-of-folds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="number-of-repeats" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="repeat" type="{http://openml.org/task}repeat" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "cross-validation", propOrder = {
    "numberOfFolds",
    "numberOfRepeats",
    "repeat"
})
public class CrossValidation {

    @XmlElement(name = "number-of-folds")
    protected int numberOfFolds;
    @XmlElement(name = "number-of-repeats")
    protected int numberOfRepeats;
    @XmlElement(required = true)
    protected List<Repeat> repeat;

    /**
     * Gets the value of the numberOfFolds property.
     * 
     */
    public int getNumberOfFolds() {
        return numberOfFolds;
    }

    /**
     * Sets the value of the numberOfFolds property.
     * 
     */
    public void setNumberOfFolds(int value) {
        this.numberOfFolds = value;
    }

    /**
     * Gets the value of the numberOfRepeats property.
     * 
     */
    public int getNumberOfRepeats() {
        return numberOfRepeats;
    }

    /**
     * Sets the value of the numberOfRepeats property.
     * 
     */
    public void setNumberOfRepeats(int value) {
        this.numberOfRepeats = value;
    }

    /**
     * Gets the value of the repeat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the repeat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRepeat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Repeat }
     * 
     * 
     */
    public List<Repeat> getRepeat() {
        if (repeat == null) {
            repeat = new ArrayList<Repeat>();
        }
        return this.repeat;
    }

}
