//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.27 at 12:54:20 PM CET 
//


package com.rapidminer.openml.task.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for evaluation-method complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="evaluation-method">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="cross-validation" type="{http://openml.org/task}cross-validation" minOccurs="0"/>
 *         &lt;element name="hold-out" type="{http://openml.org/task}hold-out" minOccurs="0"/>
 *         &lt;element name="boot-straping" type="{http://openml.org/task}bootstrapping" minOccurs="0"/>
 *         &lt;element name="sub-sampling" type="{http://openml.org/task}sub-sampling" minOccurs="0"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "evaluation-method", propOrder = {
    "crossValidation",
    "holdOut",
    "bootStraping",
    "subSampling"
})
public class EvaluationMethod {

    @XmlElement(name = "cross-validation")
    protected CrossValidation crossValidation;
    @XmlElement(name = "hold-out")
    protected HoldOut holdOut;
    @XmlElement(name = "boot-straping")
    protected Bootstrapping bootStraping;
    @XmlElement(name = "sub-sampling")
    protected SubSampling subSampling;

    /**
     * Gets the value of the crossValidation property.
     * 
     * @return
     *     possible object is
     *     {@link CrossValidation }
     *     
     */
    public CrossValidation getCrossValidation() {
        return crossValidation;
    }

    /**
     * Sets the value of the crossValidation property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossValidation }
     *     
     */
    public void setCrossValidation(CrossValidation value) {
        this.crossValidation = value;
    }

    /**
     * Gets the value of the holdOut property.
     * 
     * @return
     *     possible object is
     *     {@link HoldOut }
     *     
     */
    public HoldOut getHoldOut() {
        return holdOut;
    }

    /**
     * Sets the value of the holdOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link HoldOut }
     *     
     */
    public void setHoldOut(HoldOut value) {
        this.holdOut = value;
    }

    /**
     * Gets the value of the bootStraping property.
     * 
     * @return
     *     possible object is
     *     {@link Bootstrapping }
     *     
     */
    public Bootstrapping getBootStraping() {
        return bootStraping;
    }

    /**
     * Sets the value of the bootStraping property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bootstrapping }
     *     
     */
    public void setBootStraping(Bootstrapping value) {
        this.bootStraping = value;
    }

    /**
     * Gets the value of the subSampling property.
     * 
     * @return
     *     possible object is
     *     {@link SubSampling }
     *     
     */
    public SubSampling getSubSampling() {
        return subSampling;
    }

    /**
     * Sets the value of the subSampling property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubSampling }
     *     
     */
    public void setSubSampling(SubSampling value) {
        this.subSampling = value;
    }

}
