//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.27 at 12:54:20 PM CET 
//


package com.rapidminer.openml.task.jaxb.beans;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fold complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fold">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fold-id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fold-train" type="{http://openml.org/task}fold-train"/>
 *         &lt;element name="fold-test" type="{http://openml.org/task}fold-test"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fold", propOrder = {
    "foldId",
    "foldTrain",
    "foldTest"
})
public class Fold {

    @XmlElement(name = "fold-id")
    protected int foldId;
    @XmlElement(name = "fold-train", required = true)
    protected FoldTrain foldTrain;
    @XmlElement(name = "fold-test", required = true)
    protected FoldTest foldTest;

    /**
     * Gets the value of the foldId property.
     * 
     */
    public int getFoldId() {
        return foldId;
    }

    /**
     * Sets the value of the foldId property.
     * 
     */
    public void setFoldId(int value) {
        this.foldId = value;
    }

    /**
     * Gets the value of the foldTrain property.
     * 
     * @return
     *     possible object is
     *     {@link FoldTrain }
     *     
     */
    public FoldTrain getFoldTrain() {
        return foldTrain;
    }

    /**
     * Sets the value of the foldTrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoldTrain }
     *     
     */
    public void setFoldTrain(FoldTrain value) {
        this.foldTrain = value;
    }

    /**
     * Gets the value of the foldTest property.
     * 
     * @return
     *     possible object is
     *     {@link FoldTest }
     *     
     */
    public FoldTest getFoldTest() {
        return foldTest;
    }

    /**
     * Sets the value of the foldTest property.
     * 
     * @param value
     *     allowed object is
     *     {@link FoldTest }
     *     
     */
    public void setFoldTest(FoldTest value) {
        this.foldTest = value;
    }

}
