//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.27 at 12:54:20 PM CET 
//


package com.rapidminer.openml.task.jaxb.beans;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rapidminer.openml.task.jaxb.beans package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DataSetDescription_QNAME = new QName("http://openml.org/data-des-description", "data-set-description");
    private final static QName _Task_QNAME = new QName("http://openml.org/task", "task");
    private final static QName _RowId_QNAME = new QName("http://openml.org/task", "row-id");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rapidminer.openml.task.jaxb.beans
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DataSetDescription }
     * 
     */
    public DataSetDescription createDataSetDescription() {
        return new DataSetDescription();
    }

    /**
     * Create an instance of {@link DataSet }
     * 
     */
    public DataSet createDataSet() {
        return new DataSet();
    }

    /**
     * Create an instance of {@link FoldTest }
     * 
     */
    public FoldTest createFoldTest() {
        return new FoldTest();
    }

    /**
     * Create an instance of {@link HoldOut }
     * 
     */
    public HoldOut createHoldOut() {
        return new HoldOut();
    }

    /**
     * Create an instance of {@link CrossValidation }
     * 
     */
    public CrossValidation createCrossValidation() {
        return new CrossValidation();
    }

    /**
     * Create an instance of {@link SubSampling }
     * 
     */
    public SubSampling createSubSampling() {
        return new SubSampling();
    }

    /**
     * Create an instance of {@link Fold }
     * 
     */
    public Fold createFold() {
        return new Fold();
    }

    /**
     * Create an instance of {@link EvaluationMeasures }
     * 
     */
    public EvaluationMeasures createEvaluationMeasures() {
        return new EvaluationMeasures();
    }

    /**
     * Create an instance of {@link Task }
     * 
     */
    public Task createTask() {
        return new Task();
    }

    /**
     * Create an instance of {@link Bootstrapping }
     * 
     */
    public Bootstrapping createBootstrapping() {
        return new Bootstrapping();
    }

    /**
     * Create an instance of {@link Prediction }
     * 
     */
    public Prediction createPrediction() {
        return new Prediction();
    }

    /**
     * Create an instance of {@link Repeat }
     * 
     */
    public Repeat createRepeat() {
        return new Repeat();
    }

    /**
     * Create an instance of {@link EvaluationMethod }
     * 
     */
    public EvaluationMethod createEvaluationMethod() {
        return new EvaluationMethod();
    }

    /**
     * Create an instance of {@link FoldTrain }
     * 
     */
    public FoldTrain createFoldTrain() {
        return new FoldTrain();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataSetDescription }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openml.org/data-des-description", name = "data-set-description")
    public JAXBElement<DataSetDescription> createDataSetDescription(DataSetDescription value) {
        return new JAXBElement<DataSetDescription>(_DataSetDescription_QNAME, DataSetDescription.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Task }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openml.org/task", name = "task")
    public JAXBElement<Task> createTask(Task value) {
        return new JAXBElement<Task>(_Task_QNAME, Task.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://openml.org/task", name = "row-id")
    public JAXBElement<Long> createRowId(Long value) {
        return new JAXBElement<Long>(_RowId_QNAME, Long.class, null, value);
    }

}
