//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.27 at 12:54:20 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://openml.org/task", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.rapidminer.openml.task.jaxb.beans;
