downloadOpenMLDataSetDescription = function(id, file) {
  id = convertInteger(id)
  checkArg(id, "integer", len = 1L, na.ok = FALSE)
  checkArg(file, "character", len = 1L, na.ok = FALSE)
  url = getServerFunctionURL("openml.data.description", data.id = id)
  text = getURL(url)
  cat(file = file, text)
  invisible(NULL)
}

parseOpenMLDataSetDescription = function(file) {
  checkArg(file, "character", len = 1L, na.ok = FALSE)
  doc = xmlParse(file)
  url = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:url")[[1]])
  data = data.frame()
  
  args = list()
  args[["id"]] = as.integer(xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:id")[[1]]))
  args[["name"]] = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:name")[[1]])
  args[["version"]] = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:version")[[1]])
  args[["creator"]] = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:creator")[[1]])
  args[["contributor"]] = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:contributor")[[1]])
  args[["description"]] = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:description")[[1]])
  args[["language"]] = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:language")[[1]])
  args[["format"]] = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:format")[[1]])
  args[["licence"]] = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:licence")[[1]])
    # FIXME: will there be a date?, yes autogenerated by db
  args[["date"]] = "sss"
  args[["url"]] = url
  args[["row.id.attribute"]] = xmlOValS(doc, "/oml:data_set_description/oml:row_id_attribute")
  args[["md5.checksum"]] = xmlValue(getNodeSet(doc, "/oml:data_set_description/oml:md5_checksum")[[1]])
  args[["data.set"]] = data
  print(str(args))
  print(55)
  print(xmlOValS(doc, "/oml:data_set_description/oml:row_id_attribute"))
  dsd = do.call(OpenMLDataSetDescription, args)
  convertOpenMLDataSetDescription(dsd)
}

convertOpenMLDataSetDescription = function(dsd) {
  dsd
}
