<?php
    $active="tutorial";
    require_once("header.php");
    require_once("api/helper.php");
    ?>
<div class="container">
    <div class="marketing" style="margin-top:10px;margin-left:auto;margin-right:auto;">
        <h1>OpenML API</h1>
        <p class="marketing-byline">connect, create</p>
    </div>
    <hr class="softennarrow" />
    <!-- Docs nav
        ================================================== -->
    <div class="row">
        <div class="span3 bs-docs-sidebar" style="min-height:600px;">
            <ul class="nav nav-list bs-docs-sidenav">

<li class="nav-header">authenticate</li>
<li class="onlychild"><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_authenticate">openml.authenticate</a></li>

<li class="nav-header">data</li>
<li class="topchild "><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_data_description">openml.data.description</a></li>
<li class=""><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_data_features">openml.data.features</a></li>
<li class=""><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_data_licences">openml.data.licences</a></li>
<li class=" bottomchild"><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_data_upload">openml.data.upload</a></li>

<li class="nav-header">Tasks</li>
<li class="topchild "><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_tasks_types">openml.tasks.types</a></li>
<li class=""><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_tasks_type_search">openml.tasks.type.search</a></li>
<li class=" bottomchild"><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_tasks_search">openml.tasks.search</a></li>

<li class="nav-header">implementations</li>
<li class="topchild "><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_implementation_licences">openml.implementation.licences</a></li>
<li class=""><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_implementation_upload">openml.implementation.upload</a></li>
<li class=" bottomchild"><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_implementation_get">openml.implementation.get</a></li>

<li class="nav-header">evaluations</li>
<li class="topchild "><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_evaluation_measures">openml.evaluation.measures</a></li>
<li class=" bottomchild"><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_evaluation_methods">openml.evaluation.methods</a></li>

<li class="nav-header">runs</li>
<li class="onlychild"><a href="<?php echo $_SERVER['SCRIPT_NAME'] ?>#openml_run_upload">openml.run.upload</a></li>



			</ul>
        </div>
        <div class="span9">
            <div class="tab-content2">
                <h2>REST Services <small></small></h2>
                <p>REST is the simplest request format to use - it's a simple HTTP GET or POST action. The REST Endpoint URL is <pre>http://expdb.cs.kuleuven.be/expdb/api/</pre></p>
                <p>For instance, to request the <code>openml.data.description</code> service, invoke like this:<pre>http://expdb.cs.kuleuven.be/expdb/api/?f=openml.data.description&data_id=1</pre></p>
                <p>Responses are always in XML format, also when an error is generated by the system. Error messages will look like this:
<pre>&lt;oml:error xmlns:oml="http://openml.org/error"&gt;
  &lt;oml:code&gt;100&lt;/oml:code&gt;
  &lt;oml:message&gt;Please invoke legal function&lt;/oml:message&gt;
  &lt;oml:additional_information&gt;Additional information, not always available. &lt;/oml:additional_information&gt;
&lt;/oml:error&gt;
</pre>
				The error codes and messages are explained in the appropriate function. </p>
				
<section id="openml_authenticate">
<h3>openml.authenticate <small>returns a session_hash, which can be used for writing to the API</small></h3>
<h5>Arguments</h5>
<dl><dt><code>POST username</code> (Required)</dt><dd>The username to be authenticated with</dd></dl>
<dl><dt><code>POST password</code> (Required)</dt><dd>An md5 hash of the password, corresponding to the username</dd></dl>
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:authenticate xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:session_hash&gt;CYWJBLVYIPQ42IGB1NHSTGP181Y4TQIWE45GGQ4P&lt;/oml:session_hash&gt;
  &lt;oml:valid_until&gt;2020-01-01 00:00:00&lt;/oml:valid_until&gt;
&lt;/oml:authenticate&gt;

</pre>
<h5>Error codes</h5>
<dl><dt>250: Please provide username</dt><dd>Please provide the username as a POST variable</dd></dl>
<dl><dt>251: Please provide password</dt><dd>Please provide the password (hashed as a MD5) as a POST variable</dd></dl>
<dl><dt>252: Authentication failed</dt><dd>The username and password did not match any record in the database. Please note that the password should be hashed using md5</dd></dl>
</section>


<section id="openml_data_description">
<h3>openml.data.description <small>returns dataset descriptions in XML</small></h3>
<h5>Arguments</h5>
<dl><dt><code>GET data_id</code> (Required)</dt><dd>The dataset id</dd></dl>
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:data_set_description xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:id&gt;719290&lt;/oml:id&gt;
  &lt;oml:name&gt;Auto 93&lt;/oml:name&gt;
  &lt;oml:version&gt;1.2&lt;/oml:version&gt;
  &lt;oml:description&gt;This is a great dataset for classification!&lt;/oml:description&gt;
  &lt;oml:format&gt;arff&lt;/oml:format&gt;
  &lt;oml:creator&gt;StatLib library&lt;/oml:creator&gt;
  &lt;oml:creator&gt;UCI crew -test entry-&lt;/oml:creator&gt;
  &lt;oml:contributor&gt;Jan N. van Rijn&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Joaquin Vanschoren&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;RapidMiner Community&lt;/oml:contributor&gt;
  &lt;oml:collection_date&gt;Juny, 2006&lt;/oml:collection_date&gt;
  &lt;oml:upload_date&gt;2013-01-30 10:08:28&lt;/oml:upload_date&gt;
  &lt;oml:language&gt;English&lt;/oml:language&gt;
  &lt;oml:licence&gt;UCI&lt;/oml:licence&gt;
  &lt;oml:url&gt;http://expdb.cs.kuleuven.be/expdb/data/dataset/api/auto93_9.arff&lt;/oml:url&gt;
  &lt;oml:row_id_attribute&gt;mpg&lt;/oml:row_id_attribute&gt;
  &lt;oml:md5_checksum&gt;b031a685d8d40136449d94365f9a8b81&lt;/oml:md5_checksum&gt;
&lt;/oml:data_set_description&gt;

</pre>
<h5>Error codes</h5>
<dl><dt>110: Please provide data_id</dt><dd>Please provide data_id</dd></dl>
<dl><dt>111: Unknown dataset</dt><dd>Data set description with data_id was not found in the database</dd></dl>
</section>

<section id="openml_data_features">
<h3>openml.data.features <small>returns the features, or attributes, of a given dataset</small></h3>
<h5>Arguments</h5>
<dl><dt><code>GET data_id</code> (Required)</dt><dd>The dataset id</dd></dl>
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:data_set_features xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:data_set&gt;
    &lt;oml:id&gt;61&lt;/oml:id&gt;
    &lt;oml:name&gt;iris&lt;/oml:name&gt;
  &lt;/oml:data_set&gt;
  &lt;oml:feature&gt;
    &lt;oml:name&gt;sepallength&lt;/oml:name&gt;
    &lt;oml:data_type&gt;numeric&lt;/oml:data_type&gt;
    &lt;oml:index&gt;0&lt;/oml:index&gt;
  &lt;/oml:feature&gt;
  &lt;oml:feature&gt;
    &lt;oml:name&gt;sepalwidth&lt;/oml:name&gt;
    &lt;oml:data_type&gt;numeric&lt;/oml:data_type&gt;
    &lt;oml:index&gt;1&lt;/oml:index&gt;
  &lt;/oml:feature&gt;
  &lt;oml:feature&gt;
    &lt;oml:name&gt;petallength&lt;/oml:name&gt;
    &lt;oml:data_type&gt;numeric&lt;/oml:data_type&gt;
    &lt;oml:index&gt;2&lt;/oml:index&gt;
  &lt;/oml:feature&gt;
  &lt;oml:feature&gt;
    &lt;oml:name&gt;petalwidth&lt;/oml:name&gt;
    &lt;oml:data_type&gt;numeric&lt;/oml:data_type&gt;
    &lt;oml:index&gt;3&lt;/oml:index&gt;
  &lt;/oml:feature&gt;
  &lt;oml:feature&gt;
    &lt;oml:name&gt;class&lt;/oml:name&gt;
    &lt;oml:data_type&gt;nominal&lt;/oml:data_type&gt;
    &lt;oml:index&gt;4&lt;/oml:index&gt;
  &lt;/oml:feature&gt;
&lt;/oml:data_set_features&gt;

</pre>
<h5>Error codes</h5>
<dl><dt>270: Please provide data_id</dt><dd>Please provide data_id</dd></dl>
<dl><dt>271: Unknown dataset</dt><dd>Data set description with data_id was not found in the database</dd></dl>
<dl><dt>272: No features found</dt><dd>The registered dataset did not contain any features</dd></dl>
</section>

<section id="openml_data_licences">
<h3>openml.data.licences <small>returns a list of known data licences</small></h3>
<h5>Arguments</h5>
None
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:data_licences xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:licences&gt;
    &lt;oml:licence&gt;public domain&lt;/oml:licence&gt;
    &lt;oml:licence&gt;UCI&lt;/oml:licence&gt;
  &lt;/oml:licences&gt;
&lt;/oml:data_licences&gt;

</pre>
<h5>Error codes</h5>
None
</section>

<section id="openml_data_upload">
<h3>openml.data.upload <small>uploads and registers new datasets</small></h3>
<h5>Arguments</h5>
<dl><dt><code>POST description</code> (Required)</dt><dd>An XML file containing the data set description</dd></dl>
<dl><dt><code>POST dataset</code> (Required)</dt><dd>The dataset file to be stored on the server</dd></dl>
<dl><dt><code>POST session_hash</code> (Required)</dt><dd>The session hash, provided by the server on authentication (1 hour valid)</dd></dl>
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:upload_data_set xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:id&gt;719294&lt;/oml:id&gt;
&lt;/oml:upload_data_set&gt;

</pre>
<h5>Error codes</h5>
<dl><dt>130: Problem with file uploading</dt><dd>There was a problem with the file upload</dd></dl>
<dl><dt>131: Problem validating uploaded description file</dt><dd>The XML description format does not meet the standards</dd></dl>
<dl><dt>132: Failed to move the files</dt><dd>Internal server error, please contact api administrators</dd></dl>
<dl><dt>133: Failed to make checksum of datafile</dt><dd>Internal server error, please contact api administrators</dd></dl>
<dl><dt>134: Failed to insert record in database</dt><dd>Internal server error, please contact api administrators</dd></dl>
<dl><dt>135: Please provide description xml</dt><dd>Please provide description xml</dd></dl>
<dl><dt>136: Error slot open</dt><dd>Error slot open, will be filled by not yet defined error</dd></dl>
<dl><dt>137: Please provide session_hash</dt><dd>In order to share content, please authenticate (openml.authenticate) and provide session_hash</dd></dl>
<dl><dt>138: Authentication failed</dt><dd>The session_hash was not valid. Please try to login again, or contact api administrators</dd></dl>
<dl><dt>139: Combination name / version already exists</dt><dd>The combination of name and version of this dataset already exists. Leave version out for auto increment</dd></dl>
<dl><dt>140: Both dataset file and dataset url provided. Please provide only one</dt><dd>The system is confused since both a dataset file (post) and a dataset url (xml) are provided. Please remove one</dd></dl>
<dl><dt>141: Neither dataset file or dataset url are provided</dt><dd>Please provide either a dataset file as POST variable, xor a dataset url in the description XML</dd></dl>
</section>


<section id="openml_tasks_types">
<h3>openml.tasks.types <small>returns a list of known machine learning task types</small></h3>
<h5>Arguments</h5>
None
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:task_types xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:task_type&gt;
    &lt;oml:id&gt;1&lt;/oml:id&gt;
    &lt;oml:name&gt;Supervised Classification&lt;/oml:name&gt;
    &lt;oml:description&gt;Given a dataset with a classification target and a set of train/test splits, e.g. generated by a cross-validation procedure, train a model and return the predictions of that model.&lt;/oml:description&gt;
    &lt;oml:creator&gt;Joaquin Vanschoren&lt;/oml:creator&gt;
  &lt;/oml:task_type&gt;
&lt;/oml:task_types&gt;

</pre>
<h5>Error codes</h5>
None
</section>

<section id="openml_tasks_type_search">
<h3>openml.tasks.type.search <small>returns a definition (template) of a certain task type</small></h3>
<h5>Arguments</h5>
<dl><dt><code>GET task_type_id</code> (Required)</dt><dd>The task type id</dd></dl>
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:task_type xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:id&gt;1&lt;/oml:id&gt;
  &lt;oml:name&gt;Supervised Classification&lt;/oml:name&gt;
  &lt;oml:description&gt;Given a dataset with a classification target and a set of train/test splits, e.g. generated by a cross-validation procedure, train a model and return the predictions of that model.&lt;/oml:description&gt;
  &lt;oml:creator&gt;Joaquin Vanschoren&lt;/oml:creator&gt;
  &lt;oml:contributor&gt;Jan van Rijn&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Bo Gao&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Simon Fisher&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Venkatesh Umaashankar&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Luis Torgo&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Bernd Bischl&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Michael Berthold&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Bernd Wiswedel&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Patrick Winter&lt;/oml:contributor&gt;
  &lt;oml:date&gt;21-01-2013&lt;/oml:date&gt;
  &lt;oml:input name="source_data"&gt;
    &lt;oml:description&gt;The source data used to evaluate the model&lt;/oml:description&gt;
    &lt;oml:data_set&gt;
      &lt;oml:data_set_id&gt;input:1&lt;/oml:data_set_id&gt;
      &lt;oml:target_feature&gt;input:2&lt;/oml:target_feature&gt;
    &lt;/oml:data_set&gt;
  &lt;/oml:input&gt;
  &lt;oml:input name="estimation_procedure"&gt;
    &lt;oml:description&gt;The evaluation procedure used to evaluate the model&lt;/oml:description&gt;
    &lt;oml:estimation_procedure&gt;
      &lt;oml:type&gt;input:3&lt;/oml:type&gt;
      &lt;oml:data_splits_url&gt;input:4&lt;/oml:data_splits_url&gt;
      &lt;oml:parameter name="number_folds"&gt;input:6&lt;/oml:parameter&gt;
      &lt;oml:parameter name="number_repeats"&gt;input:5&lt;/oml:parameter&gt;
      &lt;oml:parameter name="stratified_sampling"&gt;true&lt;/oml:parameter&gt;
    &lt;/oml:estimation_procedure&gt;
  &lt;/oml:input&gt;
  &lt;oml:input name="evaluation_measures"&gt;
    &lt;oml:description&gt;Optional. A list of evaluation measures to optimize for&lt;/oml:description&gt;
    &lt;oml:evaluation_measures&gt;input:8&lt;/oml:evaluation_measures&gt;
  &lt;/oml:input&gt;
  &lt;oml:output name="predictions"&gt;
    &lt;oml:description&gt;The predictions returned by your implementation.&lt;/oml:description&gt;
    &lt;oml:predictions&gt;
      &lt;oml:format&gt;ARFF&lt;/oml:format&gt;
      &lt;oml:feature name="confidence.classname" type="numeric"/&gt;
      &lt;oml:feature name="fold" type="integer"/&gt;
      &lt;oml:feature name="prediction" type="string"/&gt;
      &lt;oml:feature name="repeat" type="integer"/&gt;
      &lt;oml:feature name="row_id" type="integer"/&gt;
    &lt;/oml:predictions&gt;
  &lt;/oml:output&gt;
&lt;/oml:task_type&gt;

</pre>
<h5>Error codes</h5>
<dl><dt>240: Please provide task_type_id</dt><dd>Please provide task_type_id</dd></dl>
<dl><dt>241: Unknown task type</dt><dd>The task type with this id was not found in the database</dd></dl>
</section>

<section id="openml_tasks_search">
<h3>openml.tasks.search <small>returns tasks in XML</small></h3>
<h5>Arguments</h5>
<dl><dt><code>GET task_id</code> (Required)</dt><dd>The task id</dd></dl>
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:task xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:task_id&gt;1&lt;/oml:task_id&gt;
  &lt;oml:task_type&gt;Supervised Classification&lt;/oml:task_type&gt;
  &lt;oml:input name="source_data"&gt;
    &lt;oml:data_set&gt;
      &lt;oml:data_set_id&gt;61&lt;/oml:data_set_id&gt;
      &lt;oml:target_feature&gt;class&lt;/oml:target_feature&gt;
    &lt;/oml:data_set&gt;
  &lt;/oml:input&gt;
  &lt;oml:input name="estimation_procedure"&gt;
    &lt;oml:estimation_procedure&gt;
      &lt;oml:type&gt;cross_validation&lt;/oml:type&gt;
      &lt;oml:data_splits_url&gt;http://expdb.cs.kuleuven.be/expdb/data/splits/iris_splits_CV_10_2.arff&lt;/oml:data_splits_url&gt;
      &lt;oml:parameter name="number_folds"&gt;10&lt;/oml:parameter&gt;
      &lt;oml:parameter name="number_repeats"&gt;2&lt;/oml:parameter&gt;
      &lt;oml:parameter name="stratified_sampling"&gt;true&lt;/oml:parameter&gt;
    &lt;/oml:estimation_procedure&gt;
  &lt;/oml:input&gt;
  &lt;oml:input name="evaluation_measures"&gt;
    &lt;oml:evaluation_measures&gt;
      &lt;oml:evaluation_measure&gt;predictive_accuracy&lt;/oml:evaluation_measure&gt;
    &lt;/oml:evaluation_measures&gt;
  &lt;/oml:input&gt;
  &lt;oml:output name="predictions"&gt;
    &lt;oml:predictions&gt;
      &lt;oml:format&gt;ARFF&lt;/oml:format&gt;
      &lt;oml:feature name="confidence.classname" type="numeric"/&gt;
      &lt;oml:feature name="fold" type="integer"/&gt;
      &lt;oml:feature name="prediction" type="string"/&gt;
      &lt;oml:feature name="repeat" type="integer"/&gt;
      &lt;oml:feature name="row_id" type="integer"/&gt;
    &lt;/oml:predictions&gt;
  &lt;/oml:output&gt;
&lt;/oml:task&gt;

</pre>
<h5>Error codes</h5>
<dl><dt>150: Please provide task_id</dt><dd>Please provide task_id</dd></dl>
<dl><dt>151: Unknown task</dt><dd>The task with this id was not found in the database</dd></dl>
</section>


<section id="openml_implementation_licences">
<h3>openml.implementation.licences <small>returns a list of known implementation licences</small></h3>
<h5>Arguments</h5>
None
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:implementation_licences xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:licences&gt;
    &lt;oml:licence&gt;public domain&lt;/oml:licence&gt;
  &lt;/oml:licences&gt;
&lt;/oml:implementation_licences&gt;

</pre>
<h5>Error codes</h5>
None
</section>

<section id="openml_implementation_upload">
<h3>openml.implementation.upload <small>uploads and registers new implementations</small></h3>
<h5>Arguments</h5>
<dl><dt><code>POST description</code> (Required)</dt><dd>An XML file containing the implementation meta data</dd></dl>
<dl><dt><code>POST source</code></dt><dd>The source code of the implementation. If multiple files, please zip them. Either source or binary is required.</dd></dl>
<dl><dt><code>POST binary</code></dt><dd>The binary of the implementation. If multiple files, please zip them. Either source or binary is required.</dd></dl>
<dl><dt><code>POST session_hash</code> (Required)</dt><dd>The session hash, provided by the server on authentication (1 hour valid)</dd></dl>
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:upload_implementation xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:id&gt;knime.janvanrijn.solveTaskA_1.5.10&lt;/oml:id&gt;
&lt;/oml:upload_implementation&gt;

</pre>
<h5>Error codes</h5>
<dl><dt>160: Error in file uploading</dt><dd>There was a problem with the file upload</dd></dl>
<dl><dt>161: Please provide description xml</dt><dd>Please provide description xml</dd></dl>
<dl><dt>162: Please provide source or binary file</dt><dd>Please provide source or binary file. It is also allowed to upload both</dd></dl>
<dl><dt>163: Problem validating uploaded description file</dt><dd>The XML description format does not meet the standards</dd></dl>
<dl><dt>164: Implementation already stored in database</dt><dd>Please change name or version number</dd></dl>
<dl><dt>165: Failed to move the files</dt><dd>Internal server error, please contact api administrators</dd></dl>
<dl><dt>166: Failed to add implementation to database</dt><dd>Internal server error, please contact api administrators</dd></dl>
<dl><dt>167: Illegal files uploaded</dt><dd>An non required file was uploaded.</dd></dl>
<dl><dt>168: The provided md5 hash equals not the server generated md5 hash of the file</dt><dd>The provided md5 hash equals not the server generated md5 hash of the file</dd></dl>
<dl><dt>169: Please provide session_hash</dt><dd>In order to share content, please authenticate (openml.authenticate) and provide session_hash</dd></dl>
<dl><dt>170: Authentication failed</dt><dd>The session_hash was not valid. Please try to login again, or contact api administrators</dd></dl>
</section>

<section id="openml_implementation_get">
<h3>openml.implementation.get <small>returns the description file of an implementation</small></h3>
<h5>Arguments</h5>
<dl><dt><code>GET implementation_id</code> (Required)</dt><dd>The implementation id (typically: name_version)</dd></dl>
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:implementation xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:id&gt;knime.janvanrijn.solveTaskA_1.5.9&lt;/oml:id&gt;
  &lt;oml:uploader&gt;-1&lt;/oml:uploader&gt;
  &lt;oml:name&gt;knime.janvanrijn.solveTaskA&lt;/oml:name&gt;
  &lt;oml:version&gt;1.5.9&lt;/oml:version&gt;
  &lt;oml:description&gt;Solving task A in an ingenious way&lt;/oml:description&gt;
  &lt;oml:creator&gt;Jan N. van Rijn&lt;/oml:creator&gt;
  &lt;oml:creator&gt;Bo Gao&lt;/oml:creator&gt;
  &lt;oml:contributor&gt;Joaquin Vanschoren&lt;/oml:contributor&gt;
  &lt;oml:contributor&gt;Patrick Winter&lt;/oml:contributor&gt;
  &lt;oml:upload_date&gt;2013-01-30 10:49:16&lt;/oml:upload_date&gt;
  &lt;oml:licence&gt;public domain&lt;/oml:licence&gt;
  &lt;oml:language&gt;English&lt;/oml:language&gt;
  &lt;oml:full_description&gt;Solving task A in an ingenious way&lt;/oml:full_description&gt;
  &lt;oml:installation_notes&gt;Download and run 'make install'&lt;/oml:installation_notes&gt;
  &lt;oml:dependencies&gt;KNIME 2.7.1&lt;/oml:dependencies&gt;
  &lt;oml:bibliographical_reference&gt;
    &lt;oml:citation&gt;free form&lt;/oml:citation&gt;
    &lt;oml:url&gt;www.janvanrijn.eu/taskA&lt;/oml:url&gt;
  &lt;/oml:bibliographical_reference&gt;
  &lt;oml:components&gt;
    &lt;oml:implementation xmlns:oml="http://open-ml.org/openml"&gt;
      &lt;oml:id&gt;knime.algorithmA_4.0&lt;/oml:id&gt;
      &lt;oml:uploader&gt;-1&lt;/oml:uploader&gt;
      &lt;oml:name&gt;knime.algorithmA&lt;/oml:name&gt;
      &lt;oml:version&gt;4.0&lt;/oml:version&gt;
      &lt;oml:description&gt;Implementation of SVM&lt;/oml:description&gt;
      &lt;oml:contributor/&gt;
      &lt;oml:upload_date&gt;2013-01-24 17:39:13&lt;/oml:upload_date&gt;
      &lt;oml:dependencies&gt;KNIME 2.7.1&lt;/oml:dependencies&gt;
      &lt;oml:parameter&gt;
        &lt;oml:name&gt;C&lt;/oml:name&gt;
        &lt;oml:data_type&gt;float&lt;/oml:data_type&gt;
        &lt;oml:default_value&gt;0.01&lt;/oml:default_value&gt;
        &lt;oml:description&gt;Controls complexity&lt;/oml:description&gt;
      &lt;/oml:parameter&gt;
    &lt;/oml:implementation&gt;
  &lt;/oml:components&gt;
  &lt;oml:source_url&gt;http://expdb.cs.kuleuven.be/expdb/data/implementation/source/run_1.xml&lt;/oml:source_url&gt;
  &lt;oml:binary_url&gt;http://expdb.cs.kuleuven.be/expdb/data/implementation/binary/run_1.xml&lt;/oml:binary_url&gt;
  &lt;oml:source_format&gt;xml&lt;/oml:source_format&gt;
  &lt;oml:source_md5&gt;474e9941a87469ec2bd2bdb327235b05&lt;/oml:source_md5&gt;
  &lt;oml:binary_md5&gt;474e9941a87469ec2bd2bdb327235b05&lt;/oml:binary_md5&gt;
&lt;/oml:implementation&gt;

</pre>
<h5>Error codes</h5>
<dl><dt>180: Please provide implementation_id</dt><dd>Please provide implementation_id</dd></dl>
<dl><dt>181: Unknown implementation</dt><dd>The implementation with this ID was not found in the database</dd></dl>
</section>


<section id="openml_evaluation_measures">
<h3>openml.evaluation.measures <small>returns a list of supported evaluation measures</small></h3>
<h5>Arguments</h5>
None
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:evaluation_measures xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:measures&gt;
    &lt;oml:measure&gt;area_under_roc_curve&lt;/oml:measure&gt;
    &lt;oml:measure&gt;average_cost&lt;/oml:measure&gt;
    &lt;oml:measure&gt;build_cpu_time&lt;/oml:measure&gt;
    &lt;oml:measure&gt;build_memory&lt;/oml:measure&gt;
    &lt;oml:measure&gt;class_complexity&lt;/oml:measure&gt;
    &lt;oml:measure&gt;class_complexity_gain&lt;/oml:measure&gt;
    &lt;oml:measure&gt;confusion_matrix&lt;/oml:measure&gt;
    &lt;oml:measure&gt;correlation_coefficient&lt;/oml:measure&gt;
    &lt;oml:measure&gt;f_measure&lt;/oml:measure&gt;
    &lt;oml:measure&gt;kappa&lt;/oml:measure&gt;
    &lt;oml:measure&gt;kb_relative_information_score&lt;/oml:measure&gt;
    &lt;oml:measure&gt;kohavi_wolpert_bias_squared&lt;/oml:measure&gt;
    &lt;oml:measure&gt;kohavi_wolpert_error&lt;/oml:measure&gt;
    &lt;oml:measure&gt;kohavi_wolpert_sigma_squared&lt;/oml:measure&gt;
    &lt;oml:measure&gt;kohavi_wolpert_variance&lt;/oml:measure&gt;
    &lt;oml:measure&gt;kononenko_bratko_information_score&lt;/oml:measure&gt;
    &lt;oml:measure&gt;matthews_correlation_coefficient&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_absolute_error&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_area_under_roc_curve&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_class_complexity&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_class_complexity_gain&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_f_measure&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_kononenko_bratko_information_score&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_precision&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_prior_absolute_error&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_prior_class_complexity&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_recall&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_weighted_f_measure&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_weighted_precision&lt;/oml:measure&gt;
    &lt;oml:measure&gt;mean_weighted_recall&lt;/oml:measure&gt;
    &lt;oml:measure&gt;precision&lt;/oml:measure&gt;
    &lt;oml:measure&gt;predictive_accuracy&lt;/oml:measure&gt;
    &lt;oml:measure&gt;prior_class_complexity&lt;/oml:measure&gt;
    &lt;oml:measure&gt;prior_entropy&lt;/oml:measure&gt;
    &lt;oml:measure&gt;recall&lt;/oml:measure&gt;
    &lt;oml:measure&gt;relative_absolute_error&lt;/oml:measure&gt;
    &lt;oml:measure&gt;root_mean_prior_squared_error&lt;/oml:measure&gt;
    &lt;oml:measure&gt;root_mean_squared_error&lt;/oml:measure&gt;
    &lt;oml:measure&gt;root_relative_squared_error&lt;/oml:measure&gt;
    &lt;oml:measure&gt;run_cpu_time&lt;/oml:measure&gt;
    &lt;oml:measure&gt;run_memory&lt;/oml:measure&gt;
    &lt;oml:measure&gt;run_virtual_memory&lt;/oml:measure&gt;
    &lt;oml:measure&gt;single_point_area_under_roc_curve&lt;/oml:measure&gt;
    &lt;oml:measure&gt;total_cost&lt;/oml:measure&gt;
    &lt;oml:measure&gt;unclassified_instance_count&lt;/oml:measure&gt;
    &lt;oml:measure&gt;webb_bias&lt;/oml:measure&gt;
    &lt;oml:measure&gt;webb_error&lt;/oml:measure&gt;
    &lt;oml:measure&gt;webb_variance&lt;/oml:measure&gt;
  &lt;/oml:measures&gt;
&lt;/oml:evaluation_measures&gt;

</pre>
<h5>Error codes</h5>
None
</section>

<section id="openml_evaluation_methods">
<h3>openml.evaluation.methods <small>returns a list of supported evaluation methods</small></h3>
<h5>Arguments</h5>
None
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:evaluation_methods xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:methods&gt;
    &lt;oml:method&gt;
      &lt;oml:type&gt;cross_validation&lt;/oml:type&gt;
      &lt;oml:folds&gt;undefined&lt;/oml:folds&gt;
      &lt;oml:repeats&gt;undefined&lt;/oml:repeats&gt;
    &lt;/oml:method&gt;
  &lt;/oml:methods&gt;
&lt;/oml:evaluation_methods&gt;

</pre>
<h5>Error codes</h5>
None
</section>


<section id="openml_run_upload">
<h3>openml.run.upload <small>uploads new runs</small></h3>
<h5>Arguments</h5>
<dl><dt><code>POST description</code> (Required)</dt><dd>An XML file describing the run</dd></dl>
<dl><dt><code>POST &lt;output_files&gt;</code> (Required)</dt><dd>All output files that should be generated by the run, as described in the task xml. For supervised classification tasks, this is typically a file containing predictions</dd></dl>
<dl><dt><code>POST session_hash</code> (Required)</dt><dd>The session hash, provided by the server on authentication (1 hour valid)</dd></dl>
<h5>Example Response</h5><pre class="pre-scrollable">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
&lt;oml:upload_run xmlns:oml="http://open-ml.org/openml"&gt;
  &lt;oml:run_id&gt;718193&lt;/oml:run_id&gt;
&lt;/oml:upload_run&gt;

</pre>
<h5>Error codes</h5>
<dl><dt>200: Please provide session_hash</dt><dd>In order to share content, please authenticate (openml.authenticate) and provide session_hash</dd></dl>
<dl><dt>201: Authentication failed</dt><dd>The session_hash was not valid. Please try to login again, or contact api administrators</dd></dl>
<dl><dt>202: Please provide run xml</dt><dd>Please provide run xml</dd></dl>
<dl><dt>203: Could not validate run xml by xsd</dt><dd>Please double check that the xml is valid. </dd></dl>
<dl><dt>204: Unknown task</dt><dd>The task with this id was not found in the database</dd></dl>
<dl><dt>205: Unknown implementation</dt><dd>The implementation with this id was not found in the database</dd></dl>
<dl><dt>206: Invalid number of files</dt><dd>The number of uploaded files did not match the number of files expected for this task type</dd></dl>
<dl><dt>207: File upload failed</dt><dd>One of the files uploaded has a problem</dd></dl>
<dl><dt>208: Error inserting setup record</dt><dd>Internal server error, please contact api administrators</dd></dl>
<dl><dt>209: Unable to store cvrun</dt><dd>Internal server error, please contact api administrators</dd></dl>
<dl><dt>210: Unable to store run</dt><dd>Internal server error, please contact api administrators</dd></dl>
<dl><dt>211: Dataset not in databse</dt><dd>One of the datasets of this task was not included in database, please contact api administrators</dd></dl>
<dl><dt>212: Unable to store file</dt><dd>Internal server error, please contact api administrators</dd></dl>
<dl><dt>213: Parameter in run xml unknown</dt><dd>One of the parameters provided in the run xml is not registered as parameter for the implementation nor its components</dd></dl>
<dl><dt>214: Unable to store input setting</dt><dd>Internal server error, please contact API support team</dd></dl>
</section>




			</div>
        </div>
        <!-- end span9 -->
    </div>
    <!-- end row -->
</div>
<!-- end container -->
<?php require_once("footer.php");?>